 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/attendaces", type: :request do
  # Attendace. As you add validations to Attendace, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Attendace.create! valid_attributes
      get attendaces_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      attendace = Attendace.create! valid_attributes
      get attendace_url(attendace)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_attendace_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      attendace = Attendace.create! valid_attributes
      get edit_attendace_url(attendace)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Attendace" do
        expect {
          post attendaces_url, params: { attendace: valid_attributes }
        }.to change(Attendace, :count).by(1)
      end

      it "redirects to the created attendace" do
        post attendaces_url, params: { attendace: valid_attributes }
        expect(response).to redirect_to(attendace_url(Attendace.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Attendace" do
        expect {
          post attendaces_url, params: { attendace: invalid_attributes }
        }.to change(Attendace, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post attendaces_url, params: { attendace: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested attendace" do
        attendace = Attendace.create! valid_attributes
        patch attendace_url(attendace), params: { attendace: new_attributes }
        attendace.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the attendace" do
        attendace = Attendace.create! valid_attributes
        patch attendace_url(attendace), params: { attendace: new_attributes }
        attendace.reload
        expect(response).to redirect_to(attendace_url(attendace))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        attendace = Attendace.create! valid_attributes
        patch attendace_url(attendace), params: { attendace: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested attendace" do
      attendace = Attendace.create! valid_attributes
      expect {
        delete attendace_url(attendace)
      }.to change(Attendace, :count).by(-1)
    end

    it "redirects to the attendaces list" do
      attendace = Attendace.create! valid_attributes
      delete attendace_url(attendace)
      expect(response).to redirect_to(attendaces_url)
    end
  end
end
